title: Cousins
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://mpcousins/github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: pretty

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: mpcousins
   twitter: onomattypeter
   facebook: mattcousins
   email: matt@mattcousins.co.uk

google_analytics: "UA-58263416-1"
