title: Cousins
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://mpcousins/github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: pretty

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

collections:
  recipes:
    output: true

social:
<<<<<<< HEAD
   github:
   twitter: onoMattyPeter
   facebook:
   email:
=======
   github: mpcousins
   twitter: onomattypeter
   facebook: mattcousins
   email: matt@mattcousins.co.uk
>>>>>>> origin/gh-pages

google_analytics: "UA--1"
