title: Cousins
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://mpcousins.github.io/cousins
baseurl: "http://mpcousins.github.io/cousins"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

collections:
  recipes:
    output: true

social:
   github:
   twitter: onoMattyPeter
   facebook:
   email:

google_analytics: "UA--1"
